name: jcode-front

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      HARBOR_REGISTRY: harbor.jbnu.ac.kr
      HARBOR_PROJECT: jsh2256
      IMAGE_NAME: jcode-front
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: Harbor 로그인
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      
      - name: 버전 설정
        run: echo "VERSION=latest" >> $GITHUB_ENV
      
      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}